- name: variable preferences
  hosts: localhost
  # vars: #play level vars
  #   Wishes: "Morning from play level"
  # vars_files: #var from file
  # - vars.yaml
  vars_prompt: #vars from prompt
  - name : WISHES
    prompt: please enter wishes
    private: false
  tasks:
  - name: print msg
    vars: #vars from task level
    ansible.builtin.debug:
      msg: "Hi, Good {{Wishes}}"


#1.Arguments
#2.Var file
#3.play level var
#4.Inventory