- name: variable preferences
  hosts: localhost
  # vars: #play level vars
  #   Wishes: "Morning from play level"
  # vars_files: #var from file
  # - vars.yaml
  vars_prompt: #vars from prompt
  - name : Wishes
    prompt: please enter wishes
    private: false
  tasks:
  - name: print msg
    # vars: #vars from task level
    #   Wishes: "Morning from task level"
    ansible.builtin.debug:
      msg: "Hi, Good {{Wishes}}"


