- name: datatypes
  hosts: localhost
  vars:
    Course: "DevOps with AWS" #String
    Tools: #list
    - shell
    - ansible
    - terraform
    Experience:
      Devops: 3 #number
      Aws: 2
      Docker: 1
    Real Project: True #boolean
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi course is: {{Course}} and tools: {{Tools}} and eperience is: {{Experienc}} and real project: {{Real Project}}"
