- name: default
  hosts: localhost
  tasks:
  - name: using default filter
    ansible.builtin.debug:
      msg: "Hi {{Name | default('Avinash')}}"

- name: uppercase
  hosts: localhost
  # vars:
  #   wishes: "Hello Avinash"
  tasks:
  - name: using uppercase filter
    ansible.builtin.debug:
      msg: "{{ 'Avinash'| upper }}"

- name: lowercase
  hosts: localhost
  vars:
    wishes: "Hello Avinash"
  tasks:
  - name: using lowercase filter
    ansible.builtin.debug:
      msg: "{{ wishes | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1,1,1,2,3,3,3,4,5,6,7,7]
  tasks:
  - name: using unique filter
    ansible.builtin.debug:
      msg: "{{numbers|unique}}"

- name: print min and max
  hosts: localhost
  vars:
    ages: [25,35,45,55,65,85,95,105]
  tasks:
  - name: using min and max filter
    ansible.builtin.debug:
      msg: "min age is: {{ages|min}}, max ages is: {{ages|max}}"

