- name: default
  hosts: localhost
  tasks:
  - name: using default filter
    ansible.builtin.debug:
      msg: "Hi {{Name | default('Avinash')}}"

- name: uppercase
  hosts: localhost
  vars:
    wishes: "Hello Avinash"
  tasks:
  - name: using uppercase filter
    ansible.builtin.debug:
      msg: "{{ wishes | uppercase }}"