- name: advanced loop
  hosts: localhost
  tasks:
  - name: installing packages
    ansible.builtin.dnf:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - { name:'nginx', state:'absent'}
    - { name:'postfix', state:'latest'}