- name: advanced loop
  hosts: localhost
  tasks:
  - name: using advanced loop and installing
    ansible.builtin.dnf:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name:'nginx', state:'absent'}
    - {name:'postfix', state:'latest'}